/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as InvoiceTokenRouteImport } from './routes/invoice.$token'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageLeadsRouteImport } from './routes/manage.leads'
import { Route as OrderNumberRouteImport } from './routes/order.$number'
import { Route as ApiWebhooksSquareRouteImport } from './routes/api.webhooks.square'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ManageInvoicesIndexRouteImport } from './routes/manage.invoices.index'
import { Route as ManageInvoicesIdRouteImport } from './routes/manage.invoices.$id'
import { Route as ManageInvoicesNewRouteImport } from './routes/manage.invoices.new'
import { Route as ManageOrdersIndexRouteImport } from './routes/manage.orders.index'
import { Route as ManageOrdersNumberRouteImport } from './routes/manage.orders.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTokenRoute = InvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageLeadsRoute = ManageLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ManageRoute,
} as any)
const OrderNumberRoute = OrderNumberRouteImport.update({
  id: '/order/$number',
  path: '/order/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSquareRoute = ApiWebhooksSquareRouteImport.update({
  id: '/api/webhooks/square',
  path: '/api/webhooks/square',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageInvoicesIndexRoute = ManageInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageInvoicesIdRoute = ManageInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => ManageRoute,
} as any)
const ManageInvoicesNewRoute = ManageInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => ManageRoute,
} as any)
const ManageOrdersIndexRoute = ManageOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageOrdersNumberRoute = ManageOrdersNumberRouteImport.update({
  id: '/orders/$number',
  path: '/orders/$number',
  getParentRoute: () => ManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/manage': typeof ManageRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-login': typeof StaffLoginRoute
  '/track': typeof TrackRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/manage/leads': typeof ManageLeadsRoute
  '/order/$number': typeof OrderNumberRoute
  '/manage/': typeof ManageIndexRoute
  '/api/webhooks/square': typeof ApiWebhooksSquareRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/manage/invoices/$id': typeof ManageInvoicesIdRoute
  '/manage/invoices/new': typeof ManageInvoicesNewRoute
  '/manage/orders/$number': typeof ManageOrdersNumberRoute
  '/manage/invoices/': typeof ManageInvoicesIndexRoute
  '/manage/orders/': typeof ManageOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-login': typeof StaffLoginRoute
  '/track': typeof TrackRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/manage/leads': typeof ManageLeadsRoute
  '/order/$number': typeof OrderNumberRoute
  '/manage': typeof ManageIndexRoute
  '/api/webhooks/square': typeof ApiWebhooksSquareRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/manage/invoices/$id': typeof ManageInvoicesIdRoute
  '/manage/invoices/new': typeof ManageInvoicesNewRoute
  '/manage/orders/$number': typeof ManageOrdersNumberRoute
  '/manage/invoices': typeof ManageInvoicesIndexRoute
  '/manage/orders': typeof ManageOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/manage': typeof ManageRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-login': typeof StaffLoginRoute
  '/track': typeof TrackRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/manage/leads': typeof ManageLeadsRoute
  '/order/$number': typeof OrderNumberRoute
  '/manage/': typeof ManageIndexRoute
  '/api/webhooks/square': typeof ApiWebhooksSquareRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/manage/invoices/$id': typeof ManageInvoicesIdRoute
  '/manage/invoices/new': typeof ManageInvoicesNewRoute
  '/manage/orders/$number': typeof ManageOrdersNumberRoute
  '/manage/invoices/': typeof ManageInvoicesIndexRoute
  '/manage/orders/': typeof ManageOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/manage'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/staff-login'
    | '/track'
    | '/invoice/$token'
    | '/manage/leads'
    | '/order/$number'
    | '/manage/'
    | '/api/webhooks/square'
    | '/api/webhooks/stripe'
    | '/manage/invoices/$id'
    | '/manage/invoices/new'
    | '/manage/orders/$number'
    | '/manage/invoices/'
    | '/manage/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/staff-login'
    | '/track'
    | '/invoice/$token'
    | '/manage/leads'
    | '/order/$number'
    | '/manage'
    | '/api/webhooks/square'
    | '/api/webhooks/stripe'
    | '/manage/invoices/$id'
    | '/manage/invoices/new'
    | '/manage/orders/$number'
    | '/manage/invoices'
    | '/manage/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/manage'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/staff-login'
    | '/track'
    | '/invoice/$token'
    | '/manage/leads'
    | '/order/$number'
    | '/manage/'
    | '/api/webhooks/square'
    | '/api/webhooks/stripe'
    | '/manage/invoices/$id'
    | '/manage/invoices/new'
    | '/manage/orders/$number'
    | '/manage/invoices/'
    | '/manage/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ManageRoute: typeof ManageRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffLoginRoute: typeof StaffLoginRoute
  TrackRoute: typeof TrackRoute
  InvoiceTokenRoute: typeof InvoiceTokenRoute
  OrderNumberRoute: typeof OrderNumberRoute
  ApiWebhooksSquareRoute: typeof ApiWebhooksSquareRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$token': {
      id: '/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/invoice/$token'
      preLoaderRoute: typeof InvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/leads': {
      id: '/manage/leads'
      path: '/leads'
      fullPath: '/manage/leads'
      preLoaderRoute: typeof ManageLeadsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/order/$number': {
      id: '/order/$number'
      path: '/order/$number'
      fullPath: '/order/$number'
      preLoaderRoute: typeof OrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/square': {
      id: '/api/webhooks/square'
      path: '/api/webhooks/square'
      fullPath: '/api/webhooks/square'
      preLoaderRoute: typeof ApiWebhooksSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/invoices/': {
      id: '/manage/invoices/'
      path: '/invoices'
      fullPath: '/manage/invoices/'
      preLoaderRoute: typeof ManageInvoicesIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/invoices/$id': {
      id: '/manage/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/manage/invoices/$id'
      preLoaderRoute: typeof ManageInvoicesIdRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/invoices/new': {
      id: '/manage/invoices/new'
      path: '/invoices/new'
      fullPath: '/manage/invoices/new'
      preLoaderRoute: typeof ManageInvoicesNewRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/orders/': {
      id: '/manage/orders/'
      path: '/orders'
      fullPath: '/manage/orders/'
      preLoaderRoute: typeof ManageOrdersIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/orders/$number': {
      id: '/manage/orders/$number'
      path: '/orders/$number'
      fullPath: '/manage/orders/$number'
      preLoaderRoute: typeof ManageOrdersNumberRouteImport
      parentRoute: typeof ManageRoute
    }
  }
}

interface ManageRouteChildren {
  ManageLeadsRoute: typeof ManageLeadsRoute
  ManageIndexRoute: typeof ManageIndexRoute
  ManageInvoicesIdRoute: typeof ManageInvoicesIdRoute
  ManageInvoicesNewRoute: typeof ManageInvoicesNewRoute
  ManageOrdersNumberRoute: typeof ManageOrdersNumberRoute
  ManageInvoicesIndexRoute: typeof ManageInvoicesIndexRoute
  ManageOrdersIndexRoute: typeof ManageOrdersIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageLeadsRoute: ManageLeadsRoute,
  ManageIndexRoute: ManageIndexRoute,
  ManageInvoicesIdRoute: ManageInvoicesIdRoute,
  ManageInvoicesNewRoute: ManageInvoicesNewRoute,
  ManageOrdersNumberRoute: ManageOrdersNumberRoute,
  ManageInvoicesIndexRoute: ManageInvoicesIndexRoute,
  ManageOrdersIndexRoute: ManageOrdersIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ManageRoute: ManageRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffLoginRoute: StaffLoginRoute,
  TrackRoute: TrackRoute,
  InvoiceTokenRoute: InvoiceTokenRoute,
  OrderNumberRoute: OrderNumberRoute,
  ApiWebhooksSquareRoute: ApiWebhooksSquareRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
